sudo: required
language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  # install deps
  - yarn install

script:
  - yarn test --watchAll=false
  - yarn build
  # build docker images
  - docker build -t brianpolanco/medimarket -f Dockerfile.prod .
  - docker tag brianpolanco/medimarket registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    #push to dockerhub
    docker push brianpolanco/medimarket;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME;
  on:
    branch: master
# APP NAME medimarket-tendencias
# TOKEN 59cbdc73-820e-4940-a5d6-614617399907

# ONLY APPLY TO THIS BRANCH
branches:
  only:
    - master

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
