version: "3"
services:
  react-ui:
    container_name: final-tendencias
    build:
      context: .
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - .:/app/
      - /app/node_modules
