# build environment
FROM node:alpine as build
WORKDIR /app
RUN npm install -g serve
# ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN yarn 
# RUN npm ci --silent
COPY . ./
RUN yarn build

# production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80
CMD serve -p $PORT -s dist
